# Generated by Django 2.0.6 on 2019-02-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chid_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom_first_name', models.CharField(max_length=100)),
                ('mom_last_name', models.CharField(max_length=100)),
                ('mom_phone_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_mom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise1.Mom'),
        ),
    ]
